ADMIN_KEY_PHRASE = 'WINTERMUTE'
NO_USERNAME_WARNING = 'Для продолжения работы с ботом, пожалуйста, запилите себе username в настройках телеграм!'
DEFAULT_ANS = 'Я вас не понимаю.\nНажмите /start чтобы начать жизнь с чистого листа ☘️'
quiz_next_button = 'next question ➡️'
quiz_back_button = '⬅️ previous question'
quiz_submit_button = 'submit quiz'
quiz_main_menu_button = 'main menu'
quiz_show_ans_button = 'show current answers'
quiz_enter = '🐟 Сдать квиз 🐠'
quiz_check = '🐌 Проверить квиз 🐌'
quiz_estimates = '🐝 Оценки за квизы 🐝'

hw_enter = '🐟 Сдать дз 🐠'
hw_check = '🐌 Проверить дз 🐌'
hw_estimates = '🐝 Оценки за дз 🐝'

ask_question = '🦉 Задать вопрос 🦉'